# Generated by Django 6.0.3 on 2026-03-22 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_passengers', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_currently_at', to='network.node')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driven_trips', to=settings.AUTH_USER_MODEL)),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_ending', to='network.node')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_starting', to='network.node')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarpoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('offered', 'Driver Offered'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dropoff_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoffs', to='network.node')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_requests', to=settings.AUTH_USER_MODEL)),
                ('pickup_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='network.node')),
                ('confirmed_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpool_requests', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('visited', models.BooleanField(default=False)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.node')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_nodes', to='trips.trip')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('trip', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CarpoolOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detour_nodes', models.IntegerField(default=0)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('route_with_passenger', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='trips.carpoolrequest')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='trips.trip')),
            ],
            options={
                'ordering': ['detour_nodes', 'fare'],
                'unique_together': {('request', 'trip')},
            },
        ),
    ]
